Belt_Reviewer/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url( r'^', include( 'apps.login.urls', namespace="login" ) ),
    url( r'^', include( 'apps.book_reviews.urls', namespace="book_reviews" ) ),
]

apps/book_reviews/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # render
    url(r'^books$', views.index, name="index"),
    # render
    url(r'^books/add$', views.add_book, name="add_book"),
    # render
    url(r'^books/(?P<id>\d+)$', views.view_book, name="view_book"),
    # render
    url(r'^users/(?P<id>\d+)$', views.view_user, name="view_user"),
    # render (DEBUG)
    url(r'^models_view$', views.models_view, name="models_view"),

    # action
    url(r'^books/add_review$', views.add_review, name="add_review"),
    # action
    url(r'^books/delete_review/(?P<id>\d+)$', views.delete_review, name="delete_review"),
    # action
    url(r'^books/add_book_and_review$', views.add_book_and_review, name="add_book_and_review"),

    # redirect
    url(r'^', views.catcher, name="catcher"),
]

apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # render
    url(r'^$', views.index, name="index"),

    # action
    url(r'^register$', views.register, name="register"),
    # action
    url(r'^login$', views.login, name="login"),
    # action
    url(r'^logout$', views.logout, name="logout"),

    # redirect
    # url(r'^', views.catcher, name="catcher"),
]

apps/book_reviews/models.py
from __future__ import unicode_literals

from django.db import models
## aggregate functions
# from django.db.models import Count
## ORM tables from other apps
from ..login.models import Users

############################## Authors ##############################

class AuthorsManager( models.Manager ):
    def add( self, name ):
        authors = self.filter( name = name )
        if authors:
            return authors[0]
        else:
            return self.create( name = name )

class Authors( models.Model ):
    name = models.CharField( max_length = 255 )
    created_at = models.DateTimeField( auto_now_add = True )
    updated_at = models.DateTimeField( auto_now = True )

    objects = AuthorsManager()

############################## Books ##############################

class BooksManager( models.Manager ):
    def add( self, title, author ):
        books = self.filter( title = title )
        if books:
            return books[0]
        else:
            return self.create( title = title, author = author )

    def add_book_and_review( self, user_id, postData ):
        errors = []

        # validate title
        if len( postData['title'] ) < 1:
            errors.append( "The title field is empty" )

        # validate author
        if postData['choose_author'] == "unselected" and len( postData['new_author'] ) < 1:
            errors.append( "No author is selected or entered (to be added)" )

        # validate review
        if len( postData['review'] ) < 1:
            errors.append( "The review field is empty" )

        # validate rating
        if postData['rating'] == "unselected":
            errors.append( "A rating must be selected" )

        if errors:
            return {
                'status': False,
                'errors': errors,
            }
        else:
            # get/create author
            author = None
            if postData['choose_author'] == "unselected":
                author = Authors.objects.add( postData['new_author'] )
            else:
                author = Authors.objects.add( postData['choose_author'] )
            # get/create book (using above author)
            book = self.add(
                postData['title'],
                author,
            )
            # create review (using above book)
            Reviews.objects.add(
                postData['review'],
                postData['rating'],
                Users.objects.get( id = user_id ),
                book,
            )

            return {
                'status': True,
                'book': book,
            }

class Books( models.Model ):
    title = models.CharField( max_length = 255 )
    author = models.ForeignKey( Authors, related_name = "authored_books" )
    created_at = models.DateTimeField( auto_now_add = True )
    updated_at = models.DateTimeField( auto_now = True )

    objects = BooksManager()

############################## Reviews ##############################

class ReviewsManager( models.Manager ):
    def add( self, comments, rating, author, book ):
        return self.create( comments = comments, rating = rating, author = author, book = book )

    def add_review( self, user_id, postData ):
        errors = []

        # validate review
        if len( postData['review'] ) < 1:
            errors.append( "The review field is empty" )

        # validate rating
        if postData['rating'] == "unselected":
            errors.append( "A rating must be selected" )

        if errors:
            return {
                'status': False,
                'errors': errors,
            }
        else:
            return {
                'status': True,
                'review': self.create(
                    comments = postData['review'],
                    rating = postData['rating'],
                    author = Users.objects.get( id = user_id ),
                    book = Books.objects.get( id = int( postData['book_id'] ) ),
                )
            }

    def remove( self, id ):
        if len( self.filter( id = id ) ) == 1:
            self.get( id = id ).delete()
        return True

    def recent( self ):
        return self.order_by( '-created_at' )[:3]

class Reviews( models.Model ):
    rating = models.IntegerField()
    comments = models.TextField()
    author = models.ForeignKey( Users, related_name = "authored_reviews" )
    book = models.ForeignKey( Books, related_name = "reviews" )
    created_at = models.DateTimeField( auto_now_add = True )
    updated_at = models.DateTimeField( auto_now = True )

    objects = ReviewsManager()

apps/login/models.py
from __future__ import unicode_literals

from django.db import models

import re

email_regex = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')


import bcrypt

def get_pw_hash( pw, salt = bcrypt.gensalt() ):
    return( bcrypt.hashpw( pw, salt ) )


class UsersManager( models.Manager ):
    def register( self, postData ):
        errors = []

        # validate email (raw content)
        if len( postData['email'] ) < 1:
            errors.append( "The email field is empty." )
        elif not email_regex.match( postData['email'] ):
            errors.append( "Incorrectly formatted email." )

        # validate email (not in DB)
        elif len( self.filter( email = postData['email'] ) ) > 0:
            errors.append( "The email ({}) is already used.".format( postData['email'] ) )

        # validate name (raw content)
        if len( postData['name'] ) < 1:
            errors.append( "The name field is empty." )
        # elif not postData['name'].isalpha():
        #     errors.append( "The name field can only contain letters." )

        # validate alias (raw content)
        if len( postData['alias'] ) < 1:
            errors.append( "The alias field is empty." )
        elif not postData['alias'].isalpha():
            errors.append( "The alias field can only contain letters." )

        # validate pw_1 (raw content)
        if len( postData['pw_1'] ) < 1:
            errors.append( "The password field is empty." )
        elif len( postData['pw_1'] ) < 8:
            errors.append( "The password field MUST be AT LEAST 8 characters!" )
        elif not re.match( r'^.*[A-Z]+.*$', postData['pw_1'] ):
            errors.append( "The password field MUST contain AT LEAST 1 capital letter!" )
        elif not re.match( r'^.*\d+.*$', postData['pw_1'] ):
            errors.append( "The password field MUST contain AT LEAST 1 number!" )

        # validate pw_1 against pw_2
        if postData['pw_1'] != postData['pw_2']:
            errors.append( "The password and confirm password fields MUST match!" )

        # return
        if len( errors ):
            return {
                'status': False,
                'errors': errors
            }
        else:
            return {
                'status': True,
                'user': self.create(
                    email = postData['email'],
                    name = postData['name'],
                    alias = postData['alias'],
                    password = get_pw_hash( postData['pw_1'].encode() ),
                )
            }

    def login( self, postData ):
        errors = []

        # validate email (raw content)
        if len( postData['email'] ) < 1:
            errors.append( "The email field is empty." )
        elif not email_regex.match( postData['email'] ):
            errors.append( "Incorrectly formatted email." )

        # validate email (in DB)
        elif len( self.filter( email = postData['email'] ) ) < 1:
            errors.append( "Unknown email." )

        # validate password (raw content)
        elif len( postData['pw'] ) < 1:
            errors.append( "The password field is empty." )

        # validate password (matches DB)
        else:
            user = self.get( email = postData['email'] )
            if get_pw_hash( postData['pw'].encode(), user.password.encode() ) != user.password:
                errors.append( "Incorrect email or password." )

        # return
        if len( errors ):
            return {
                'status': False,
                'errors': errors
            }
        else:
            return {
                'status': True,
                'user': self.get( email = postData['email'] )
            }

class Users( models.Model ):
    name = models.CharField( max_length = 255 )
    alias = models.CharField( max_length = 255 )
    email = models.CharField( max_length = 255 )
    password = models.CharField( max_length = 40 )
    created_at = models.DateTimeField( auto_now_add = True )
    updated_at = models.DateTimeField( auto_now = True )

    objects = UsersManager()

apps/book_reviews/views.py
from django.shortcuts import render, redirect, reverse, HttpResponse
from django.contrib import messages
from .models import Authors, Books, Reviews
from ..login.models import Users

# render
def index( request ):
    if 'login_id' in request.session:
        context = {
            'recent_reviews': Reviews.objects.recent(),
            'all_books': Books.objects.all(),
        }
        return render( request, "book_reviews/index.html", context )
    else:
        return redirect( reverse( "login:index" ) )

# render
def add_book( request ):
    if 'login_id' in request.session:
        context = {
            'all_authors': Authors.objects.all(),
        }
        return render( request, "book_reviews/add_book.html", context )
    else:
        return redirect( reverse( 'book_reviews:index' ) )

# render
def view_book( request, id ):
    if 'login_id' in request.session:
        context = {
            'book': Books.objects.get( id = id ),
        }
        return render( request, "book_reviews/view_book.html", context )
    else:
        return redirect( reverse( 'book_reviews:index' ) )

# render
def view_user( request, id ):
    if 'login_id' in request.session:
        context = {
            'user': Users.objects.get( id = id ),
            'books_reviewed': Books.objects.filter( reviews__author__id = id ).distinct(),
        }
        return render( request, "book_reviews/view_user.html", context )
    else:
        return redirect( reverse( 'book_reviews:index' ) )

# render (DEBUG)
def models_view( request ):
    if 'login_id' in request.session:
        context = {
            'all_users': Users.objects.all(),
            'all_books': Books.objects.all(),
            'all_authors': Authors.objects.all(),
            'all_reviews': Reviews.objects.all(),
        }
        return render( request, "book_reviews/models_view.html", context )
    else:
        return redirect( reverse( 'book_reviews:index' ) )

# action
def add_book_and_review( request ):
    if 'login_id' in request.session:
        if request.method == "POST":
            db_result = Books.objects.add_book_and_review( int( request.session['login_id'] ), request.POST )
            if not db_result['status']:
                for i in db_result['errors']:
                    messages.add_message( request, messages.INFO, "- " + i )
                return redirect( reverse ( "book_reviews:add_book" ) )
            else:
                return redirect( reverse ( "book_reviews:view_book", kwargs = { 'id': db_result['book'].id } ) )
        else:
            return redirect( reverse( "book_reviews:add_book" ) )
    else:
        return redirect( reverse( 'book_reviews:index' ) )

# action
def add_review( request ):
    if 'login_id' in request.session:
        if request.method == "POST":
            Reviews.objects.add_review( int( request.session['login_id'] ), request.POST )
            return redirect( request.META['HTTP_REFERER'] )
        else:
            return redirect( request.META['HTTP_REFERER'] )
    else:
        return redirect( reverse( 'book_reviews:index' ) )

# action
def delete_review( request, id ):
    if 'login_id' in request.session:
        Reviews.objects.remove( id )
        return redirect( request.META['HTTP_REFERER'] )
    else:
        return redirect( reverse( 'book_reviews:index' ) )

# redirect -> render
def catcher( request ):
    return redirect( reverse( "book_reviews:index" ) )

apps/book_reviews/templates/book_reviews/add_book.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Add Book and Reviews</title>
    {% load static %}
    {% include 'book_reviews/common/head_js.html' %}
    {% include 'book_reviews/common/head_css.html' %}
  </head>
  <body>
    <header>
      <h2 id="header_icon">CodingDojo Book Reviews</h2>
      <span>Welcome, {{ request.session.alias }}</span>
      <a href="{% url 'book_reviews:index' %}">Home</a>
      <a href="{% url 'login:logout' %}">Logout</a>
    </header>
    <main>
      <h2>Add a New Book Title and a Review:</h2>
      <form action="{% url 'book_reviews:add_book_and_review' %}" method="post">
        {% csrf_token %}
        <!-- title -->
        <label for="title">Book Title:
          <input type="text" name="title" />
        </label> <br />
        <!-- author -->
        <label for="author">Author:
          <ul type="none">
            <!-- select author -->
            <li>
              <label for="choose_author">Choose from the list:
                <select name="choose_author">
                  <option selected value="unselected">Choose author</option>
                  {% for author in all_authors %}
                    <option value="{{ author.name }}">{{ author.name }}</option>
                  {% endfor %}
                </select>
              </label>
            </li>
            <!-- add author -->
            <li>
              <label for"new_author">Or add a new other:
                <input type="text" name="new_author" />
              </label>
            </li>
          </ul>
        </label> <br />
        <!-- review -->
        <label for="review">Review:
          <textarea name="review" rows="5" cols="40"></textarea>
        </label> <br />
        <!-- rating -->
        <label for="rating">Rating:
          <select name="rating">
            <option selected value="unselected">Choose rating</option>
            <option value="0">0</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select>
          stars
        </label> <br />
        <input type="submit" value="Add Book and Review" /> <br />
        <a href="{% url 'book_reviews:index' %}"><input type="button" value="Cancel" /></a>
      </form>
    </main>
    <footer>
      {% if messages %}
        <div style="border: 1px solid red; color: red; font-weight: bold;"
          {% for message in messages %}
            <!-- Use message.tags? -->
            <p>{{ message }}</p>
          {% endfor %}
        </div>
      {% endif %}
    </footer>
    {% include 'book_reviews/common/body_footer.html' %}
  </body>
</html>

apps/book_reviews/templates/book_reviews/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Books Home</title>
    {% load static %}
    {% include 'book_reviews/common/head_js.html' %}
    {% include 'book_reviews/common/head_css.html' %}
  </head>
  <body>
    <header>
      <h2 id="header_icon">CodingDojo Book Reviews</h2>
      <span>Welcome, {{ request.session.alias }}</span>
      <a href="{% url 'book_reviews:add_book' %}">Add Book and Reviews</a>
      <a href="{% url 'login:logout' %}">Logout</a>
    </header>
    <main>
      <div id="recent_reviews" style="display: inline-block; vertical-align: top; width: 400px;">
        <h3>Recent Book Reviews:</h3>
        {% for review in recent_reviews %}
          <div>
            <p><a href="{% url 'book_reviews:view_book' id=review.book.id %}">{{ review.book.title }}</a></p>
            <ul type="none">
              <li>Rating: {{ review.rating }}</li>
              <li><a href="{% url 'book_reviews:view_user' id=review.author.id %}">{{ review.author.alias }}</a> says: {{ review.comments }}</li>
              <li>Posted on: {{ review.created_at|date:"F j, Y, g:i A" }}</li>
            </ul>
          </div>
        {% endfor %}
      </div>
      <div id="other_books_reviews" style="display: inline-block; vertical-align: top; width: 300px;">
        <h3>Other Books with Reviews:</h3>
        <div style="border: 1px solid black; width: 290px; height: 5.5rem; overflow: scroll;">
          {% for book in all_books %}
            <p><a href="{% url 'book_reviews:view_book' id=book.id %}">{{ book.title }}</a></p>
          {% endfor %}
        </div>
      </div>
    </main>
    {% include 'book_reviews/common/body_footer.html' %}
  </body>
</html>

apps/book_reviews/templates/book_reviews/models_view.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Models View</title>
  </head>
  <body>
    <table border="1">
      <caption style="text-align: left;">Users</caption>
      <thead>
        <tr>
          <th>id</th>
          <th>name</th>
          <th>alias</th>
          <th>email</th>
          <th>authored_reviews</th>
        </tr>
      </thead>
      <tbody>
        {% for user in all_users %}
          <tr>
            <td><a href="{% url 'book_reviews:view_user' id=user.id %}">{{ user.id }}</a></td>
            <td>{{ user.name }}</td>
            <td>{{ user.alias }}</td>
            <td>{{ user.email }}</td>
            <td>
              {% for review in user.authored_reviews.all %}
                {{ review.id }}
              {% endfor %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <br />

    <table border="1">
      <caption style="text-align: left;">Authors</caption>
      <thead>
        <tr>
          <th>id</th>
          <th>name</th>
          <th>authored_books</th>
        </tr>
      </thead>
      <tbody>
        {% for author in all_authors %}
          <tr>
            <td>{{ author.id }}</td>
            <td>{{ author.name }}</td>
            <td>
              {% for book in author.authored_books.all %}
                {{ book.id }}
              {% endfor %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <br />

    <table border="1">
      <caption style="text-align: left;">Books</caption>
      <thead>
        <tr>
          <th>id</th>
          <th>title</th>
          <th>author</th>
          <th>reviews</th>
        </tr>
      </thead>
      <tbody>
        {% for book in all_books %}
          <tr>
            <td><a href="{% url 'book_reviews:view_book' id=book.id %}">{{ book.id }}</a></td>
            <td>{{ book.title }}</td>
            <td>{{ book.author.name }}</td>
            <td>
              {% for review in book.reviews.all %}
                {{ review.id }}
              {% endfor %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <br />

    <table border="1">
      <caption style="text-align: left;">Reviews</caption>
      <thead>
        <tr>
          <th>id</th>
          <th>book</th>
          <th>rating</th>
          <th>comments</th>
        </tr>
      </thead>
      <tbody>
        {% for review in all_reviews %}
          <tr>
            <td>{{ review.id }}</td>
            <td>{{ review.book.title }}</td>
            <td>{{ review.rating }}</td>
            <td>{{ review.comments }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>

apps/book_reviews/templates/book_reviews/view_book.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>View Book and Reviews</title>
    {% load static %}
    {% include 'book_reviews/common/head_js.html' %}
    {% include 'book_reviews/common/head_css.html' %}
  </head>
  <body>
    <header>
      <h2 id="header_icon">CodingDojo Book Reviews</h2>
      <span>Welcome, {{ request.session.alias }}</span>
      <a href="{% url 'book_reviews:index' %}">Home</a>
      <a href="{% url 'login:logout' %}">Logout</a>
    </header>
    <main>
      <h4>{{ book.title }}</h4>
      <p>Author: {{ book.author.name }}</p>
      <div id="reviews" style="display: inline-block; vertical-align: top; width: 400px;">
        <h3>Reviews:</h3>
        {% for review in book.reviews.all %}
          <div>
            <hr />
            <p>Rating: {{ review.rating }}</p>
            <p><a href="{% url 'book_reviews:view_user' id=review.author.id %}">{{ review.author.alias }}</a> says: {{ review.comments }}</p>
            <p>Posted on: {{ review.created_at|date:"F j, Y, g:i A" }}</p>
            {% if review.author.id == request.session.login_id %}
              <a href="{% url 'book_reviews:delete_review' id=review.id %}">delete this review</a>
            {% endif %}
          </div>
        {% endfor %}
      </div>
      <div id="add_review" style="display: inline-block; vertical-align: top; width: 300px;">
        <h3>Add a Review:</h3>
        <div style="width=200px; heigh=200px;">
          <form action="{% url 'book_reviews:add_review' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="book_id" value="{{ book.id }}" />
            <!-- review -->
            <textarea name="review" rows="5" cols="40"></textarea> <br />
            <!-- rating -->
            <label for="rating">Rating:
              <select name="rating">
                <option selected value="unselected">Choose rating</option>
                <option value="0">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
              </select>
              stars
            </label> <br />
            <input type="submit" value="Submit Review" /> <br />
          </form>
        </div>
      </div>
    </main>
    {% include 'book_reviews/common/body_footer.html' %}
  </body>
</html>

apps/book_reviews/templates/book_reviews/view_user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>User Reviews</title>
    {% load static %}
    {% include 'book_reviews/common/head_js.html' %}
    {% include 'book_reviews/common/head_css.html' %}
  </head>
  <body>
    <header>
      <h2 id="header_icon">CodingDojo Book Reviews</h2>
      <span>Welcome, {{ request.session.alias }}</span>
      <a href="{% url 'book_reviews:index' %}">Home</a>
      <a href="{% url 'book_reviews:add_book' %}">Add Book and Reviews</a>
      <a href="{% url 'login:logout' %}">Logout</a>
    </header>
    <main>
      <p style="font-size: 150%;">User Alias: {{ user.alias }}</p>
      <p>Name: {{ user.name }}</p>
      <p>Email: {{ user.email }}</p>
      <p>Total Reviews: {{ user.authored_reviews.count }}</p>
      <p>Posted reviews on the following books:</p>
      <ul type="none">
        {% for book in books_reviewed %}
          <li><a href="{% url 'book_reviews:view_book' id=book.id %}">{{ book.title }}</a></li>
        {% endfor %}
      </ul>
    </main>
    {% include 'book_reviews/common/body_footer.html' %}
  </body>
</html>