Belt_Reviewer/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url( r'^', include( 'apps.login.urls', namespace="login" ) ),
    url( r'^', include( 'apps.book_reviews.urls', namespace="book_reviews" ) ),
]

apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # render
    url(r'^$', views.index, name="index"),

    # action
    url(r'^register$', views.register, name="register"),
    # action
    url(r'^login$', views.login, name="login"),
    # action
    url(r'^logout$', views.logout, name="logout"),

    # redirect
    # url(r'^', views.catcher, name="catcher"),
]

apps/login/models.py
from __future__ import unicode_literals

from django.db import models

import re

email_regex = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')


import bcrypt

def get_pw_hash( pw, salt = bcrypt.gensalt() ):
    return( bcrypt.hashpw( pw, salt ) )


class UsersManager( models.Manager ):
    def register( self, postData ):
        errors = []

        # validate email (raw content)
        if len( postData['email'] ) < 1:
            errors.append( "The email field is empty." )
        elif not email_regex.match( postData['email'] ):
            errors.append( "Incorrectly formatted email." )

        # validate email (not in DB)
        elif len( self.filter( email = postData['email'] ) ) > 0:
            errors.append( "The email ({}) is already used.".format( postData['email'] ) )

        # validate name (raw content)
        if len( postData['name'] ) < 1:
            errors.append( "The name field is empty." )
        # elif not postData['name'].isalpha():
        #     errors.append( "The name field can only contain letters." )

        # validate alias (raw content)
        if len( postData['alias'] ) < 1:
            errors.append( "The alias field is empty." )
        elif not postData['alias'].isalpha():
            errors.append( "The alias field can only contain letters." )

        # validate pw_1 (raw content)
        if len( postData['pw_1'] ) < 1:
            errors.append( "The password field is empty." )
        elif len( postData['pw_1'] ) < 8:
            errors.append( "The password field MUST be AT LEAST 8 characters!" )
        elif not re.match( r'^.*[A-Z]+.*$', postData['pw_1'] ):
            errors.append( "The password field MUST contain AT LEAST 1 capital letter!" )
        elif not re.match( r'^.*\d+.*$', postData['pw_1'] ):
            errors.append( "The password field MUST contain AT LEAST 1 number!" )

        # validate pw_1 against pw_2
        if postData['pw_1'] != postData['pw_2']:
            errors.append( "The password and confirm password fields MUST match!" )

        # return
        if len( errors ):
            return {
                'status': False,
                'errors': errors
            }
        else:
            return {
                'status': True,
                'user': self.create(
                    email = postData['email'],
                    name = postData['name'],
                    alias = postData['alias'],
                    password = get_pw_hash( postData['pw_1'].encode() ),
                )
            }

    def login( self, postData ):
        errors = []

        # validate email (raw content)
        if len( postData['email'] ) < 1:
            errors.append( "The email field is empty." )
        elif not email_regex.match( postData['email'] ):
            errors.append( "Incorrectly formatted email." )

        # validate email (in DB)
        elif len( self.filter( email = postData['email'] ) ) < 1:
            errors.append( "Unknown email." )

        # validate password (raw content)
        elif len( postData['pw'] ) < 1:
            errors.append( "The password field is empty." )

        # validate password (matches DB)
        else:
            user = self.get( email = postData['email'] )
            if get_pw_hash( postData['pw'].encode(), user.password.encode() ) != user.password:
                errors.append( "Incorrect email or password." )

        # return
        if len( errors ):
            return {
                'status': False,
                'errors': errors
            }
        else:
            return {
                'status': True,
                'user': self.get( email = postData['email'] )
            }

class Users( models.Model ):
    name = models.CharField( max_length = 255 )
    alias = models.CharField( max_length = 255 )
    email = models.CharField( max_length = 255 )
    password = models.CharField( max_length = 40 )
    created_at = models.DateTimeField( auto_now_add = True )
    updated_at = models.DateTimeField( auto_now = True )

    objects = UsersManager()

apps/login/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from .models import Users

# render
def index( request ):
    if 'login_id' in request.session:
        return redirect( "book_reviews:index" )
    else:
        return render( request, "login/index.html" )

# action
def register( request ):
    if request.method == "POST":
        db_result = Users.objects.register( request.POST )

        if not db_result['status']:
            messages.add_message( request, messages.INFO, "Unable to register!" )
            for i in db_result['errors']:
                messages.add_message( request, messages.INFO, "- " + i )
            return redirect( reverse( "login:index" ) )
        else:
            request.session['login_id'] = db_result['user'].id
            request.session['email'] = db_result['user'].email
            request.session['name'] = db_result['user'].name
            request.session['alias'] = db_result['user'].alias
            request.session['new_registration'] = 1
            return redirect( reverse( "book_reviews:index" ) )
    else:
        return redirect( reverse( "login:index" ) )

# action
def login( request ):
    if request.method == "POST":
        db_result = Users.objects.login( request.POST )

        if not db_result['status']:
            messages.add_message( request, messages.INFO, "Unable to login!" )
            for i in db_result['errors']:
                messages.add_message( request, messages.INFO, "- " + i )
            return redirect( reverse ( "login:index" ) )
        else:
            request.session['login_id'] = db_result['user'].id
            request.session['email'] = db_result['user'].email
            request.session['name'] = db_result['user'].name
            request.session['alias'] = db_result['user'].alias
            return redirect( reverse( "book_reviews:index" ) )
    else:
        return redirect( reverse( "login:index" ) )

# action
def logout( request ):
    request.session.clear()
    return redirect( reverse( "login:index" ) )

# # redirect
# def catcher( request ):
#     return redirect( reverse( "login:index" ) )

apps/login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <title>Welcome</title>
    <!-- JavaScript -- External -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" charset="utf-8"></script>
    <!-- JavaScript -- Internal -->
    <script type="text/javascript" src="{% static 'login/js/action.js' %}" charset="utf-8"></script>
    <!-- CSS -- External -->
    <link type="text/css" rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css" />
    <!-- CSS -- Internal -->
    <link type="text/css" rel="stylesheet" href="{% static 'login/css/style.css' %}" />
  </head>
  <body>
    <header>
      <h2 id="header_icon">CodingDojo Book Reviews</h2>
    </header>
    <main>
      <div id="registration">
        <form action="{% url 'login:register' %}" method="POST">
          {% csrf_token %}
          <h3>Registration:</h3>
          <div id="registration_form">
            <label>Email:</label>
            <input type="text" name="email" class="email" />
            <br />
            <label>Name:</label>
            <input type="text" name="name" class="name" />
            <br />
            <label>Alias:</label>
            <input type="text" name="alias" class="name" />
            <br />
            <label>Password:</label>
            <input type="password" name="pw_1" class="passwd" />
            <br />
            <label>Confirm Password:</label>
            <input type="password" name="pw_2" class="passwd" />
            <br />
            <input type="submit" value="Register" class="button" id="register" />
          </div>
        </form>
      </div>
      <div id="login">
        <form action="{% url 'login:login' %}" method="POST">
          {% csrf_token %}
          <h3>Login:</h3>
          <div id="login_form">
            <label>Email:</label>
            <input type="text" name="email" class="email" />
            <br />
            <label>Password:</label>
            <input type="password" name="pw" class="passwd" />
            <br />
            <input type="submit" value="Login" class="button" id="login" />
          </div>
        </form>
      </div>
      {% if messages %}
        <div style="border: 1px solid red; color: red; font-weight: bold;"
          {% for message in messages %}
            <!-- Use message.tags? -->
            <p>{{ message }}</p>
          {% endfor %}
        </div>
      {% endif %}
    </main>
  </body>
</html>